# Generated by Django 3.2 on 2021-04-15 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adresss',
            field=models.CharField(default=1, max_length=50, verbose_name='المحافظه :'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='adresss_detail',
            field=models.CharField(default=1, max_length=50, verbose_name='العنوان بالتفاصيل :'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='دكتور ؟'),
        ),
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profail', verbose_name='الصوره الشخصيه'),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_phone',
            field=models.CharField(default=0, max_length=30, verbose_name='الهاتف :'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='السعر :'),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialist_doctor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='متخصص في ؟'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subtitle',
            field=models.CharField(default=1, max_length=50, verbose_name='نبذه عنك :'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='wating_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='مده الانتظار :'),
        ),
        migrations.AddField(
            model_name='profile',
            name='whats_app',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='who_i',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='من انت'),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_hours',
            field=models.IntegerField(default=1, verbose_name='عدد ساعات العمل :'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=80, verbose_name='الاسم :'),
        ),
    ]
