# Generated by Django 3.2 on 2021-04-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210415_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type_of_person',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=20, null=True),
        ),
    ]
