# Generated by Django 3.2 on 2021-04-15 22:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_type_of_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='join_now',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 15, 22, 19, 18, 317542, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
