# Generated by Django 3.2 on 2021-04-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_join_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='working_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد ساعات العمل :'),
        ),
    ]
