# Generated by Django 3.2 on 2021-05-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210502_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='likes',
            new_name='liked',
        ),
    ]
